project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - bm-example.qmd
    - api.qmd

website:
  title: "Generative Economic Modeling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bm-example.qmd
        text: BM Example
      - href: api.qmd
        text: API

format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  package: gem
  sections:
    - title: Core API
      contents:
        - BM
        - helpers
        - surrogate
        - structures
        - plots
        - io_utils
